[package]
name = "pineapplepizza-rust-reference"
version = "0.1.0"
authors = ["Justin (:flaviusb) Marsh <justin.marsh@flaviusb.net>"]

[dependencies]
nom = "^4.1"
unicode-segmentation = "1.2.1"
serde = "1.0.60"
serde_derive = "1.0"
serde_json = "1.0.33"
